name: Upload REPL artefacts

on:
  push:
    branches:
      - rollup-swc-xiaopi
      - xiaopi-v3

permissions:
  contents: read

jobs:
  upload:
    runs-on: ubuntu-latest
    name: Upload
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4
      - name: Install Toolchain
        uses: dtolnay/rust-toolchain@stable
        # remove after or before merging rollup-swc
        if: ${{github.head_ref == 'rollup-swc'}}
        with:
          toolchain: nightly
          targets: x86_64-unknown-linux-gnu
      - name: Cache cargo
        uses: actions/cache@v3
        # remove after or before merging rollup-swc
        if: ${{github.head_ref == 'rollup-swc'}}
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            .cargo-cache
            rust/target/
          key: cargo-cache-${{ hashFiles('rust/Cargo.lock') }}
          restore-keys: cargo-cache
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts
      - name: Build artefacts
        # remove after or before merging rollup-swc
        if: ${{ github.head_ref == 'rollup-swc' }}
        run: npm exec -- concurrently -c green,blue,yellow 'npm:build:napi -- --release' 'npm run build:wasm' 'npm:build:cjs' && npm run build:copy-native && npm run build:bootstrap
      # remove after or before merging rollup-swc
      - name: Build artefacts
        if: ${{ github.head_ref != 'rollup-swc' }}
        run: npm run build:cjs && npm run build:bootstrap
      - name: SDA
        run: tree -L 1